version: 1.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Backend
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu/Backend
    owner: root
    group: root
    mode: 755

hooks:
  AfterInstall:
    - location: script/deploy-eighteen.sh
      timeout: 2000
      runas: ubuntu